<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\..\project.props" />

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>Nerosoft.Euonia.Security.Tests.BrokenFixtures</RootNamespace>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Source\Euonia.Security\Euonia.Security.csproj" />
    </ItemGroup>

</Project>
