<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\common.props" />
    <Import Project="..\resource.props" />

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Google.Protobuf" />
        <PackageReference Include="Grpc.AspNetCore" />
        <PackageReference Include="Grpc.AspNetCore.Server" />
        <PackageReference Include="Grpc.AspNetCore.Server.Reflection" />
        <PackageReference Include="Grpc.Core" />
        <PackageReference Include="Grpc.HealthCheck" />
        <PackageReference Include="Grpc.Net.Client" />
        <PackageReference Include="Microsoft.Extensions.Hosting" />
    </ItemGroup>

    <ItemGroup>
        <Protobuf CompileOutputs="true" Include="protos\nerosoft\*.proto" GrpcServices="Server" AdditionalImportDirs=".\protos" AdditionalProtocArguments="--experimental_allow_proto3_optional" />

        <None Update="protos\nerosoft\*.proto">
            <Pack>true</Pack>
            <PackagePath>content</PackagePath>
        </None>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Euonia.Bus\Euonia.Bus.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Compile Update="Properties\Resources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Resources.resx</DependentUpon>
        </Compile>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Update="Properties\Resources.resx">
            <Generator>ResXFileCodeGenerator</Generator>
            <LastGenOutput>Resources.Designer.cs</LastGenOutput>
        </EmbeddedResource>
    </ItemGroup>

</Project>
